routes:
  - country: [ 'AM' ]
    interface: _DEFAULT
    #interface: docker0
    weight: 100
  - domain: '.*\.ru'
    interface: _DEFAULT
    metric: 100
  - net: [ '0.0.0.0/0' ]
    interface: docker0
    weight: 99
  - net: [ '1.0.0.0/8' ]
    interface: docker0
    weight: 98
  - net: [ '1.1.0.0/16' ]
    interface: docker0
    weight: 97
  - net: '1.0.0.0/8'
    interface: docker0
    weight: 100
  - domain: '.*\.am'
    interface: docker0
    weight: 100
  - domain: '.*\.us'
    interface: docker0
    weight: 100
  - domain: [ '.*\.x','.*\.a' ]
    interface: docker0
    weight: 99
  - domain: [ '.*\.chatgpt.com', 'chatgpt.com' ]
    interface: docker0
    weight: 500
#    route_ttl: 10
  - net: '81.177.6.147'
    interface: docker0
    weight: 5
  - net: '81.177.6.0/24'
    interface: docker0
    weight: 6
interfaces:
  - wg-firezone
  - wg-firezone_1
pbr_mark: 200
table: 200
domain_route_ttl: 100