- name: Set entrypoint variable explicitly
  set_fact:
    entrypoint: "{{ entrypoint | default('vpn_tehinkome_ru') }}"
    mrvpn_tunnel_name: "wg_exit1"
  tags: always

- name: Debug MRVPN configuration
  debug:
    msg: |
      MRVPN Config:
        entrypoint: {{ entrypoint }}
        mrvpn_root: {{ mrvpn_root }}
        mrvpn_tunnel_name: {{ mrvpn_tunnel_name }}
        wg_tunnel_result defined: {{ wg_tunnel_result is defined }}

# Firezone is now handled by separate firezone role

- block:
    - name: Extract compose file paths for the current host
      set_fact:
        entrypoint_compose_files: >-
          {{ wg_tunnel_result | dict2items |
             map(attribute='value.hosts') |
             map('dict2items') |
             flatten |
             selectattr('key', 'equalto', entrypoint) |
             map(attribute='value.compose_file') |
             list }}
    - block:
        - include_tasks:
            file: ../../../playbooks/tasks/patch_compose.yml
          vars:
            compose_dir: "{{mrvpn_root}}"
            compose_files: "{{entrypoint_compose_files}}"
      delegate_to: "{{entrypoint}}"
      when: entrypoint_compose_files | length > 0
  tags: tunnels
  when: wg_tunnel_result is defined

- name: Compose services tasks
  block:
    - include_tasks:
        file: compose_svcs.yml
    - include_tasks:
        file: ../../../playbooks/tasks/patch_compose.yml
      vars:
        compose_dir: "{{mrvpn_root}}"
        compose_files: "{{compose_svcs_files}}"
  delegate_to: "{{entrypoint}}"
  ignore_unreachable: true
  tags: services

- name: Shutdown MRVPN compose services
  community.docker.docker_compose_v2:
    project_src: "{{mrvpn_root}}/mrvpn"
    state: absent
    remove_orphans: yes
  delegate_to: "{{entrypoint}}"
  ignore_unreachable: true
  failed_when: false
  tags: always

- name: Pull, build and start WireGuard compose services
  community.docker.docker_compose_v2:
    build: always
    pull: always
    project_src: "{{mrvpn_root}}/wg_tunnels/{{ item.key }}"
    state: present
  loop: "{{ wg_tunnel_result | dict2items }}"
  when: wg_tunnel_result is defined
  delegate_to: "{{entrypoint}}"
  ignore_unreachable: true
  failed_when: false
  tags: always

- name: Pull, build and start MRVPN compose services
  community.docker.docker_compose_v2:
    build: always
    pull: always
    project_src: "{{mrvpn_root}}/mrvpn"
    state: present
  delegate_to: "{{entrypoint}}"
  ignore_unreachable: true
  failed_when: false
  tags: always